In [1]:
import requests
from bs4 import BeautifulSoup as bs

In [2]:
requests.get('https://finance.naver.com/marketindex/exchangeList.naver')
# 200이라는 뜻은, 정상적으로 접속했고, 데이터 가져왔다는 뜻

In [4]:
# 실제 사이트에서 html 정보를 받아와서 변수에 저장
data = requests.get('https://finance.naver.com/marketindex/exchangeList.naver').text

In [5]:
# BeatifulSoup을 이용해서 데이터를 파싱
soup = bs(data, 'html.parser')

In [6]:
print(soup)

<html lang="ko">
<head>
<title>네이버 증권</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="text/javascript" http-equiv="Content-Script-Type"/>
<meta content="text/css" http-equiv="Content-Style-Type"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/finance.css" rel="stylesheet" type="text/css"/>
<script language="javascript">document.domain="naver.com";</script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/js/info/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/js/lcslog.js" type="text/javascript"></script>
</head>
<body>
<div class="tbl_area">
<table border="1" class="tbl_exchange" summary="환전 고시 환율 리스트">
<caption>환전 고시 환율</caption>
<colgroup>
<col width="162"/>
<col width="92"/>
<col width="92"/>
<col width="92"/>
<col width="93"/>
<col width="92"/>
<col width="90"/>
</colgroup>
<thead>
<tr>
<th class="th_ex1" rowspan="2">
<a href="#" onclick="javascript:changeOrder('exchange'); return false;"><span>통화명</span></a></th>
<th class="th_ex2" rowspan="2"><span>매매기준율</span></th>
<th class="th_ex3" colspan="2"><span>현찰</span></th>
<th class="th_ex4" colspan="2"><span>송금</span></th>
<th class="th_ex6" rowspan="2"><span>미화환산율</span></th>
</tr>
<tr>
<th class="th_ex7"><span>사실 때 </span></th>
<th class="th_ex8"><span>파실 때 </span></th>
<th class="th_ex9"><span>보내실 때 </span></th>
<th class="th_ex10"><span>받으실 때</span></th>
</tr>
</thead>
<tbody>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_USDKRW', '1', event);" target="_parent">




					미국 USD

				</a></td>
<td class="sale">1,315.50</td>
<td>


						1,338.52

				</td>
<td>


						1,292.48

				</td>
<td>


						1,328.30

				</td>
<td>


						1,302.70

				</td>
<td>1.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EURKRW', '2', event);" target="_parent">




					유럽연합 EUR

				</a></td>
<td class="sale">1,444.68</td>
<td>


						1,473.42

				</td>
<td>


						1,415.94

				</td>
<td>


						1,459.12

				</td>
<td>


						1,430.24

				</td>
<td>1.098</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JPYKRW', '3', event);" target="_parent">

					일본 JPY (100엔)




				</a></td>
<td class="sale">981.75</td>
<td>


						998.93

				</td>
<td>


						964.57

				</td>
<td>


						991.37

				</td>
<td>


						972.13

				</td>
<td>0.746</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CNYKRW', '4', event);" target="_parent">




					중국 CNY

				</a></td>
<td class="sale">191.29</td>
<td>


						200.85

				</td>
<td>


						181.73

				</td>
<td>


						193.20

				</td>
<td>


						189.38

				</td>
<td>0.145</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HKDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HKDKRW', '5', event);" target="_parent">




					홍콩 HKD

				</a></td>
<td class="sale">167.60</td>
<td>


						170.90

				</td>
<td>


						164.30

				</td>
<td>


						169.27

				</td>
<td>


						165.93

				</td>
<td>0.127</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TWDKRW', '6', event);" target="_parent">




					대만 TWD

				</a></td>
<td class="sale">43.15</td>
<td>


						48.80

				</td>
<td>


						38.84

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.033</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_GBPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_GBPKRW', '7', event);" target="_parent">




					영국 GBP

				</a></td>
<td class="sale">1,635.17</td>
<td>


						1,667.38

				</td>
<td>


						1,602.96

				</td>
<td>


						1,651.52

				</td>
<td>


						1,618.82

				</td>
<td>1.243</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_OMRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_OMRKRW', '8', event);" target="_parent">




					오만 OMR

				</a></td>
<td class="sale">3,416.71</td>
<td>


						3,720.79

				</td>
<td>


						3,211.71

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>2.597</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CADKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CADKRW', '9', event);" target="_parent">




					캐나다 CAD

				</a></td>
<td class="sale">982.52</td>
<td>


						1,001.87

				</td>
<td>


						963.17

				</td>
<td>


						992.34

				</td>
<td>


						972.70

				</td>
<td>0.747</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CHFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CHFKRW', '10', event);" target="_parent">




					스위스 CHF

				</a></td>
<td class="sale">1,468.27</td>
<td>


						1,497.19

				</td>
<td>


						1,439.35

				</td>
<td>


						1,482.95

				</td>
<td>


						1,453.59

				</td>
<td>1.116</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SEKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SEKKRW', '11', event);" target="_parent">




					스웨덴 SEK

				</a></td>
<td class="sale">127.52</td>
<td>


						130.64

				</td>
<td>


						124.40

				</td>
<td>


						128.79

				</td>
<td>


						126.25

				</td>
<td>0.097</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AUDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AUDKRW', '12', event);" target="_parent">




					호주 AUD

				</a></td>
<td class="sale">886.58</td>
<td>


						904.04

				</td>
<td>


						869.12

				</td>
<td>


						895.44

				</td>
<td>


						877.72

				</td>
<td>0.674</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NZDKRW', '13', event);" target="_parent">




					뉴질랜드 NZD

				</a></td>
<td class="sale">817.45</td>
<td>


						833.55

				</td>
<td>


						801.35

				</td>
<td>


						825.62

				</td>
<td>


						809.28

				</td>
<td>0.621</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CZKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CZKKRW', '14', event);" target="_parent">




					체코 CZK

				</a></td>
<td class="sale">61.62</td>
<td>


						66.85

				</td>
<td>


						56.08

				</td>
<td>


						62.29

				</td>
<td>


						60.95

				</td>
<td>0.047</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CLPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CLPKRW', '15', event);" target="_parent">




					칠레 CLP

				</a></td>
<td class="sale">1.66</td>
<td>


						1.82

				</td>
<td>


						1.50

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.001</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TRYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TRYKRW', '16', event);" target="_parent">




					튀르키예 TRY

				</a></td>
<td class="sale">67.83</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						68.57

				</td>
<td>


						67.09

				</td>
<td>0.052</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MNTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MNTKRW', '17', event);" target="_parent">




					몽골 MNT

				</a></td>
<td class="sale">0.37</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ILSKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ILSKRW', '18', event);" target="_parent">




					이스라엘 ILS

				</a></td>
<td class="sale">360.97</td>
<td>


						397.06

				</td>
<td>


						332.10

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.274</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DKKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DKKKRW', '19', event);" target="_parent">




					덴마크 DKK

				</a></td>
<td class="sale">193.87</td>
<td>


						198.61

				</td>
<td>


						189.13

				</td>
<td>


						195.80

				</td>
<td>


						191.94

				</td>
<td>0.147</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NOKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NOKKRW', '20', event);" target="_parent">




					노르웨이 NOK

				</a></td>
<td class="sale">125.50</td>
<td>


						128.57

				</td>
<td>


						122.43

				</td>
<td>


						126.75

				</td>
<td>


						124.25

				</td>
<td>0.095</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SARKRW', '21', event);" target="_parent">




					사우디아라비아 SAR

				</a></td>
<td class="sale">350.73</td>
<td>


						372.82

				</td>
<td>


						326.53

				</td>
<td>


						354.23

				</td>
<td>


						347.23

				</td>
<td>0.267</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KWDKRW', '22', event);" target="_parent">




					쿠웨이트 KWD

				</a></td>
<td class="sale">4,292.85</td>
<td>


						4,571.88

				</td>
<td>


						3,949.43

				</td>
<td>


						4,335.77

				</td>
<td>


						4,249.93

				</td>
<td>3.263</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BHDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BHDKRW', '23', event);" target="_parent">




					바레인 BHD

				</a></td>
<td class="sale">3,489.11</td>
<td>


						3,712.41

				</td>
<td>


						3,209.99

				</td>
<td>


						3,524.00

				</td>
<td>


						3,454.22

				</td>
<td>2.652</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AEDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AEDKRW', '24', event);" target="_parent">




					아랍에미리트 AED

				</a></td>
<td class="sale">358.21</td>
<td>


						377.91

				</td>
<td>


						333.50

				</td>
<td>


						361.79

				</td>
<td>


						354.63

				</td>
<td>0.272</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JODKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JODKRW', '25', event);" target="_parent">




					요르단 JOD

				</a></td>
<td class="sale">1,854.38</td>
<td>


						2,019.41

				</td>
<td>


						1,706.03

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>1.410</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EGPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EGPKRW', '26', event);" target="_parent">




					이집트 EGP

				</a></td>
<td class="sale">42.57</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.032</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_THBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_THBKRW', '27', event);" target="_parent">




					태국 THB

				</a></td>
<td class="sale">38.42</td>
<td>


						40.34

				</td>
<td>


						36.12

				</td>
<td>


						38.80

				</td>
<td>


						38.04

				</td>
<td>0.029</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SGDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SGDKRW', '28', event);" target="_parent">




					싱가포르 SGD

				</a></td>
<td class="sale">987.95</td>
<td>


						1,007.61

				</td>
<td>


						968.29

				</td>
<td>


						997.82

				</td>
<td>


						978.08

				</td>
<td>0.751</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MYRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MYRKRW', '29', event);" target="_parent">




					말레이시아 MYR

				</a></td>
<td class="sale">297.02</td>
<td>


						315.73

				</td>
<td>


						275.05

				</td>
<td>

						N/A


				</td>
<td>


						294.05

				</td>
<td>0.226</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_IDRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_IDRKRW', '30', event);" target="_parent">


					인도네시아 IDR 100



				</a></td>
<td class="sale">8.88</td>
<td>


						9.76

				</td>
<td>


						8.00

				</td>
<td>


						8.96

				</td>
<td>


						8.80

				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_QARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_QARKRW', '31', event);" target="_parent">




					카타르 QAR

				</a></td>
<td class="sale">360.59</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.274</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KZTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KZTKRW', '32', event);" target="_parent">




					카자흐스탄 KZT

				</a></td>
<td class="sale">2.91</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.002</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BNDKRW', '33', event);" target="_parent">




					브루나이 BND

				</a></td>
<td class="sale">987.95</td>
<td>


						1,027.46

				</td>
<td>


						928.68

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.751</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_INRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_INRKRW', '34', event);" target="_parent">




					인도 INR

				</a></td>
<td class="sale">16.02</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.012</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PKRKRW', '35', event);" target="_parent">




					파키스탄 PKR

				</a></td>
<td class="sale">4.63</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BDTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BDTKRW', '36', event);" target="_parent">




					방글라데시 BDT

				</a></td>
<td class="sale">12.39</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.009</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PHPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PHPKRW', '37', event);" target="_parent">




					필리핀 PHP

				</a></td>
<td class="sale">23.43</td>
<td>


						25.77

				</td>
<td>


						21.51

				</td>
<td>


						23.66

				</td>
<td>


						23.20

				</td>
<td>0.018</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MXNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MXNKRW', '38', event);" target="_parent">




					멕시코 MXN

				</a></td>
<td class="sale">72.90</td>
<td>


						80.19

				</td>
<td>


						66.78

				</td>
<td>


						73.62

				</td>
<td>


						72.18

				</td>
<td>0.055</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BRLKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BRLKRW', '39', event);" target="_parent">




					브라질 BRL

				</a></td>
<td class="sale">263.84</td>
<td>


						290.75

				</td>
<td>


						237.46

				</td>
<td>

						N/A


				</td>
<td>


						260.68

				</td>
<td>0.201</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_VNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_VNDKRW', '40', event);" target="_parent">



					베트남 VND 100


				</a></td>
<td class="sale">5.60</td>
<td>


						6.26

				</td>
<td>


						4.94

				</td>
<td>


						5.65

				</td>
<td>


						5.55

				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ZARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ZARKRW', '41', event);" target="_parent">




					남아프리카 공화국 ZAR

				</a></td>
<td class="sale">72.54</td>
<td>


						78.34

				</td>
<td>


						66.74

				</td>
<td>


						73.41

				</td>
<td>


						71.67

				</td>
<td>0.055</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_RUBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_RUBKRW', '42', event);" target="_parent">




					러시아 RUB

				</a></td>
<td class="sale">16.08</td>
<td>


						17.60

				</td>
<td>


						13.27

				</td>
<td>


						16.64

				</td>
<td>


						15.52

				</td>
<td>0.012</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HUFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HUFKRW', '43', event);" target="_parent">




					헝가리 HUF

				</a></td>
<td class="sale">3.89</td>
<td>


						4.25

				</td>
<td>


						3.58

				</td>
<td>


						3.93

				</td>
<td>


						3.85

				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PLNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PLNKRW', '44', event);" target="_parent">




					폴란드 PLN

				</a></td>
<td class="sale">311.86</td>
<td>


						336.80

				</td>
<td>


						286.92

				</td>
<td>


						315.29

				</td>
<td>


						308.43

				</td>
<td>0.237</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_LKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_LKRKRW', '45', event);" target="_parent">




					스리랑카 LKR

				</a></td>
<td class="sale">4.11</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DZDKRW', '46', event);" target="_parent">




					알제리 DZD

				</a></td>
<td class="sale">9.70</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KESKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KESKRW', '47', event);" target="_parent">




					케냐 KES

				</a></td>
<td class="sale">9.74</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_COPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_COPKRW', '48', event);" target="_parent">




					콜롬비아 COP

				</a></td>
<td class="sale">0.29</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>

In [7]:
# 하나밖에 없으니까 find로 찾는다
soup.find('tbody')
# find는 html안에서 해당 태그의 첫번째 정보를 출력
# 두번째 값을 찾으려면? - 일단 전체 가져와야 한다. find_all
# find_all() : 해당 태그의 전체 정보를 리스트의 형태로 출력

<tbody>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_USDKRW', '1', event);" target="_parent">




					미국 USD

				</a></td>
<td class="sale">1,315.50</td>
<td>


						1,338.52

				</td>
<td>


						1,292.48

				</td>
<td>


						1,328.30

				</td>
<td>


						1,302.70

				</td>
<td>1.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EURKRW', '2', event);" target="_parent">




					유럽연합 EUR

				</a></td>
<td class="sale">1,444.68</td>
<td>


						1,473.42

				</td>
<td>


						1,415.94

				</td>
<td>


						1,459.12

				</td>
<td>


						1,430.24

				</td>
<td>1.098</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JPYKRW', '3', event);" target="_parent">

					일본 JPY (100엔)




				</a></td>
<td class="sale">981.75</td>
<td>


						998.93

				</td>
<td>


						964.57

				</td>
<td>


						991.37

				</td>
<td>


						972.13

				</td>
<td>0.746</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CNYKRW', '4', event);" target="_parent">




					중국 CNY

				</a></td>
<td class="sale">191.29</td>
<td>


						200.85

				</td>
<td>


						181.73

				</td>
<td>


						193.20

				</td>
<td>


						189.38

				</td>
<td>0.145</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HKDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HKDKRW', '5', event);" target="_parent">




					홍콩 HKD

				</a></td>
<td class="sale">167.60</td>
<td>


						170.90

				</td>
<td>


						164.30

				</td>
<td>


						169.27

				</td>
<td>


						165.93

				</td>
<td>0.127</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TWDKRW', '6', event);" target="_parent">




					대만 TWD

				</a></td>
<td class="sale">43.15</td>
<td>


						48.80

				</td>
<td>


						38.84

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.033</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_GBPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_GBPKRW', '7', event);" target="_parent">




					영국 GBP

				</a></td>
<td class="sale">1,635.17</td>
<td>


						1,667.38

				</td>
<td>


						1,602.96

				</td>
<td>


						1,651.52

				</td>
<td>


						1,618.82

				</td>
<td>1.243</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_OMRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_OMRKRW', '8', event);" target="_parent">




					오만 OMR

				</a></td>
<td class="sale">3,416.71</td>
<td>


						3,720.79

				</td>
<td>


						3,211.71

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>2.597</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CADKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CADKRW', '9', event);" target="_parent">




					캐나다 CAD

				</a></td>
<td class="sale">982.52</td>
<td>


						1,001.87

				</td>
<td>


						963.17

				</td>
<td>


						992.34

				</td>
<td>


						972.70

				</td>
<td>0.747</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CHFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CHFKRW', '10', event);" target="_parent">




					스위스 CHF

				</a></td>
<td class="sale">1,468.27</td>
<td>


						1,497.19

				</td>
<td>


						1,439.35

				</td>
<td>


						1,482.95

				</td>
<td>


						1,453.59

				</td>
<td>1.116</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SEKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SEKKRW', '11', event);" target="_parent">




					스웨덴 SEK

				</a></td>
<td class="sale">127.52</td>
<td>


						130.64

				</td>
<td>


						124.40

				</td>
<td>


						128.79

				</td>
<td>


						126.25

				</td>
<td>0.097</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AUDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AUDKRW', '12', event);" target="_parent">




					호주 AUD

				</a></td>
<td class="sale">886.58</td>
<td>


						904.04

				</td>
<td>


						869.12

				</td>
<td>


						895.44

				</td>
<td>


						877.72

				</td>
<td>0.674</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NZDKRW', '13', event);" target="_parent">




					뉴질랜드 NZD

				</a></td>
<td class="sale">817.45</td>
<td>


						833.55

				</td>
<td>


						801.35

				</td>
<td>


						825.62

				</td>
<td>


						809.28

				</td>
<td>0.621</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CZKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CZKKRW', '14', event);" target="_parent">




					체코 CZK

				</a></td>
<td class="sale">61.62</td>
<td>


						66.85

				</td>
<td>


						56.08

				</td>
<td>


						62.29

				</td>
<td>


						60.95

				</td>
<td>0.047</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CLPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CLPKRW', '15', event);" target="_parent">




					칠레 CLP

				</a></td>
<td class="sale">1.66</td>
<td>


						1.82

				</td>
<td>


						1.50

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.001</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TRYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TRYKRW', '16', event);" target="_parent">




					튀르키예 TRY

				</a></td>
<td class="sale">67.83</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						68.57

				</td>
<td>


						67.09

				</td>
<td>0.052</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MNTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MNTKRW', '17', event);" target="_parent">




					몽골 MNT

				</a></td>
<td class="sale">0.37</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ILSKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ILSKRW', '18', event);" target="_parent">




					이스라엘 ILS

				</a></td>
<td class="sale">360.97</td>
<td>


						397.06

				</td>
<td>


						332.10

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.274</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DKKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DKKKRW', '19', event);" target="_parent">




					덴마크 DKK

				</a></td>
<td class="sale">193.87</td>
<td>


						198.61

				</td>
<td>


						189.13

				</td>
<td>


						195.80

				</td>
<td>


						191.94

				</td>
<td>0.147</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NOKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NOKKRW', '20', event);" target="_parent">




					노르웨이 NOK

				</a></td>
<td class="sale">125.50</td>
<td>


						128.57

				</td>
<td>


						122.43

				</td>
<td>


						126.75

				</td>
<td>


						124.25

				</td>
<td>0.095</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SARKRW', '21', event);" target="_parent">




					사우디아라비아 SAR

				</a></td>
<td class="sale">350.73</td>
<td>


						372.82

				</td>
<td>


						326.53

				</td>
<td>


						354.23

				</td>
<td>


						347.23

				</td>
<td>0.267</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KWDKRW', '22', event);" target="_parent">




					쿠웨이트 KWD

				</a></td>
<td class="sale">4,292.85</td>
<td>


						4,571.88

				</td>
<td>


						3,949.43

				</td>
<td>


						4,335.77

				</td>
<td>


						4,249.93

				</td>
<td>3.263</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BHDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BHDKRW', '23', event);" target="_parent">




					바레인 BHD

				</a></td>
<td class="sale">3,489.11</td>
<td>


						3,712.41

				</td>
<td>


						3,209.99

				</td>
<td>


						3,524.00

				</td>
<td>


						3,454.22

				</td>
<td>2.652</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AEDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AEDKRW', '24', event);" target="_parent">




					아랍에미리트 AED

				</a></td>
<td class="sale">358.21</td>
<td>


						377.91

				</td>
<td>


						333.50

				</td>
<td>


						361.79

				</td>
<td>


						354.63

				</td>
<td>0.272</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JODKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JODKRW', '25', event);" target="_parent">




					요르단 JOD

				</a></td>
<td class="sale">1,854.38</td>
<td>


						2,019.41

				</td>
<td>


						1,706.03

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>1.410</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EGPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EGPKRW', '26', event);" target="_parent">




					이집트 EGP

				</a></td>
<td class="sale">42.57</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.032</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_THBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_THBKRW', '27', event);" target="_parent">




					태국 THB

				</a></td>
<td class="sale">38.42</td>
<td>


						40.34

				</td>
<td>


						36.12

				</td>
<td>


						38.80

				</td>
<td>


						38.04

				</td>
<td>0.029</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SGDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SGDKRW', '28', event);" target="_parent">




					싱가포르 SGD

				</a></td>
<td class="sale">987.95</td>
<td>


						1,007.61

				</td>
<td>


						968.29

				</td>
<td>


						997.82

				</td>
<td>


						978.08

				</td>
<td>0.751</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MYRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MYRKRW', '29', event);" target="_parent">




					말레이시아 MYR

				</a></td>
<td class="sale">297.02</td>
<td>


						315.73

				</td>
<td>


						275.05

				</td>
<td>

						N/A


				</td>
<td>


						294.05

				</td>
<td>0.226</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_IDRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_IDRKRW', '30', event);" target="_parent">


					인도네시아 IDR 100



				</a></td>
<td class="sale">8.88</td>
<td>


						9.76

				</td>
<td>


						8.00

				</td>
<td>


						8.96

				</td>
<td>


						8.80

				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_QARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_QARKRW', '31', event);" target="_parent">




					카타르 QAR

				</a></td>
<td class="sale">360.59</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.274</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KZTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KZTKRW', '32', event);" target="_parent">




					카자흐스탄 KZT

				</a></td>
<td class="sale">2.91</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.002</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BNDKRW', '33', event);" target="_parent">




					브루나이 BND

				</a></td>
<td class="sale">987.95</td>
<td>


						1,027.46

				</td>
<td>


						928.68

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.751</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_INRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_INRKRW', '34', event);" target="_parent">




					인도 INR

				</a></td>
<td class="sale">16.02</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.012</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PKRKRW', '35', event);" target="_parent">




					파키스탄 PKR

				</a></td>
<td class="sale">4.63</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BDTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BDTKRW', '36', event);" target="_parent">




					방글라데시 BDT

				</a></td>
<td class="sale">12.39</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.009</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PHPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PHPKRW', '37', event);" target="_parent">




					필리핀 PHP

				</a></td>
<td class="sale">23.43</td>
<td>


						25.77

				</td>
<td>


						21.51

				</td>
<td>


						23.66

				</td>
<td>


						23.20

				</td>
<td>0.018</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MXNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MXNKRW', '38', event);" target="_parent">




					멕시코 MXN

				</a></td>
<td class="sale">72.90</td>
<td>


						80.19

				</td>
<td>


						66.78

				</td>
<td>


						73.62

				</td>
<td>


						72.18

				</td>
<td>0.055</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BRLKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BRLKRW', '39', event);" target="_parent">




					브라질 BRL

				</a></td>
<td class="sale">263.84</td>
<td>


						290.75

				</td>
<td>


						237.46

				</td>
<td>

						N/A


				</td>
<td>


						260.68

				</td>
<td>0.201</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_VNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_VNDKRW', '40', event);" target="_parent">



					베트남 VND 100


				</a></td>
<td class="sale">5.60</td>
<td>


						6.26

				</td>
<td>


						4.94

				</td>
<td>


						5.65

				</td>
<td>


						5.55

				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ZARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ZARKRW', '41', event);" target="_parent">




					남아프리카 공화국 ZAR

				</a></td>
<td class="sale">72.54</td>
<td>


						78.34

				</td>
<td>


						66.74

				</td>
<td>


						73.41

				</td>
<td>


						71.67

				</td>
<td>0.055</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_RUBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_RUBKRW', '42', event);" target="_parent">




					러시아 RUB

				</a></td>
<td class="sale">16.08</td>
<td>


						17.60

				</td>
<td>


						13.27

				</td>
<td>


						16.64

				</td>
<td>


						15.52

				</td>
<td>0.012</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HUFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HUFKRW', '43', event);" target="_parent">




					헝가리 HUF

				</a></td>
<td class="sale">3.89</td>
<td>


						4.25

				</td>
<td>


						3.58

				</td>
<td>


						3.93

				</td>
<td>


						3.85

				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PLNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PLNKRW', '44', event);" target="_parent">




					폴란드 PLN

				</a></td>
<td class="sale">311.86</td>
<td>


						336.80

				</td>
<td>


						286.92

				</td>
<td>


						315.29

				</td>
<td>


						308.43

				</td>
<td>0.237</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_LKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_LKRKRW', '45', event);" target="_parent">




					스리랑카 LKR

				</a></td>
<td class="sale">4.11</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DZDKRW', '46', event);" target="_parent">




					알제리 DZD

				</a></td>
<td class="sale">9.70</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KESKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KESKRW', '47', event);" target="_parent">




					케냐 KES

				</a></td>
<td class="sale">9.74</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_COPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_COPKRW', '48', event);" target="_parent">




					콜롬비아 COP

				</a></td>
<td class="sale">0.29</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TZSKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TZSKRW', '49', event);" target="_parent">




					탄자니아 TZS

				</a></td>
<td class="sale">0.56</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NPRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NPRKRW', '50', event);" target="_parent">




					네팔 NPR

				</a></td>
<td class="sale">10.02</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.008</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_RONKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_RONKRW', '51', event);" target="_parent">




					루마니아 RON

				</a></td>
<td class="sale">292.61</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.222</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_LYDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_LYDKRW', '52', event);" target="_parent">




					리비아 LYD

				</a></td>
<td class="sale">275.95</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						278.70

				</td>
<td>


						273.20

				</td>
<td>0.210</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MOPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MOPKRW', '53', event);" target="_parent">





In [25]:
# td나 tr로 쪼갠다

# td를 기준으로 출력
# soup.find_all('td')[0].get_text().replace('\n', '').strip('\t')
# find_all해서 첫번째값. 텍스트 가져오기. 줄바꿈,탭 제거

# find_all : 해당 태그의 전체 정보를 리스트의 형태로 출력
data_list = soup.find_all('td')

In [28]:
# data_list를 이용하여 2차원 배열로 새로운 리스트를 생성
# 1차원 리스트 생성
# [[7개씩], [7개씩], [7개씩], [7개씩]] -> 2차원 리스트
_list = []
for i in data_list :
    x = i.get_text()
    x = x.replace("\n", '')
    x = x.strip('\t')
    _list.append(x)
_list

['미국 USD',
 '1,315.50',
 '1,338.52',
 '1,292.48',
 '1,328.30',
 '1,302.70',
 '1.000',
 '유럽연합 EUR',
 '1,444.68',
 '1,473.42',
 '1,415.94',
 '1,459.12',
 '1,430.24',
 '1.098',
 '일본 JPY (100엔)',
 '981.75',
 '998.93',
 '964.57',
 '991.37',
 '972.13',
 '0.746',
 '중국 CNY',
 '191.29',
 '200.85',
 '181.73',
 '193.20',
 '189.38',
 '0.145',
 '홍콩 HKD',
 '167.60',
 '170.90',
 '164.30',
 '169.27',
 '165.93',
 '0.127',
 '대만 TWD',
 '43.15',
 '48.80',
 '38.84',
 'N/A',
 'N/A',
 '0.033',
 '영국 GBP',
 '1,635.17',
 '1,667.38',
 '1,602.96',
 '1,651.52',
 '1,618.82',
 '1.243',
 '오만 OMR',
 '3,416.71',
 '3,720.79',
 '3,211.71',
 'N/A',
 'N/A',
 '2.597',
 '캐나다 CAD',
 '982.52',
 '1,001.87',
 '963.17',
 '992.34',
 '972.70',
 '0.747',
 '스위스 CHF',
 '1,468.27',
 '1,497.19',
 '1,439.35',
 '1,482.95',
 '1,453.59',
 '1.116',
 '스웨덴 SEK',
 '127.52',
 '130.64',
 '124.40',
 '128.79',
 '126.25',
 '0.097',
 '호주 AUD',
 '886.58',
 '904.04',
 '869.12',
 '895.44',
 '877.72',
 '0.674',
 '뉴질랜드 NZD',
 '817.45',
 '833.55',
 '801.35',
 '825.62',
 '809.28',
 '0.621',
 '체코 CZK',
 '61.62',
 '66.85',
 '56.08',
 '62.29',
 '60.95',
 '0.047',
 '칠레 CLP',
 '1.66',
 '1.82',
 '1.50',
 'N/A',
 'N/A',
 '0.001',
 '튀르키예 TRY',
 '67.83',
 'N/A',
 'N/A',
 '68.57',
 '67.09',
 '0.052',
 '몽골 MNT',
 '0.37',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '이스라엘 ILS',
 '360.97',
 '397.06',
 '332.10',
 'N/A',
 'N/A',
 '0.274',
 '덴마크 DKK',
 '193.87',
 '198.61',
 '189.13',
 '195.80',
 '191.94',
 '0.147',
 '노르웨이 NOK',
 '125.50',
 '128.57',
 '122.43',
 '126.75',
 '124.25',
 '0.095',
 '사우디아라비아 SAR',
 '350.73',
 '372.82',
 '326.53',
 '354.23',
 '347.23',
 '0.267',
 '쿠웨이트 KWD',
 '4,292.85',
 '4,571.88',
 '3,949.43',
 '4,335.77',
 '4,249.93',
 '3.263',
 '바레인 BHD',
 '3,489.11',
 '3,712.41',
 '3,209.99',
 '3,524.00',
 '3,454.22',
 '2.652',
 '아랍에미리트 AED',
 '358.21',
 '377.91',
 '333.50',
 '361.79',
 '354.63',
 '0.272',
 '요르단 JOD',
 '1,854.38',
 '2,019.41',
 '1,706.03',
 'N/A',
 'N/A',
 '1.410',
 '이집트 EGP',
 '42.57',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.032',
 '태국 THB',
 '38.42',
 '40.34',
 '36.12',
 '38.80',
 '38.04',
 '0.029',
 '싱가포르 SGD',
 '987.95',
 '1,007.61',
 '968.29',
 '997.82',
 '978.08',
 '0.751',
 '말레이시아 MYR',
 '297.02',
 '315.73',
 '275.05',
 'N/A',
 '294.05',
 '0.226',
 '인도네시아 IDR 100',
 '8.88',
 '9.76',
 '8.00',
 '8.96',
 '8.80',
 '0.007',
 '카타르 QAR',
 '360.59',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.274',
 '카자흐스탄 KZT',
 '2.91',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.002',
 '브루나이 BND',
 '987.95',
 '1,027.46',
 '928.68',
 'N/A',
 'N/A',
 '0.751',
 '인도 INR',
 '16.02',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.012',
 '파키스탄 PKR',
 '4.63',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.004',
 '방글라데시 BDT',
 '12.39',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.009',
 '필리핀 PHP',
 '23.43',
 '25.77',
 '21.51',
 '23.66',
 '23.20',
 '0.018',
 '멕시코 MXN',
 '72.90',
 '80.19',
 '66.78',
 '73.62',
 '72.18',
 '0.055',
 '브라질 BRL',
 '263.84',
 '290.75',
 '237.46',
 'N/A',
 '260.68',
 '0.201',
 '베트남 VND 100',
 '5.60',
 '6.26',
 '4.94',
 '5.65',
 '5.55',
 '0.004',
 '남아프리카 공화국 ZAR',
 '72.54',
 '78.34',
 '66.74',
 '73.41',
 '71.67',
 '0.055',
 '러시아 RUB',
 '16.08',
 '17.60',
 '13.27',
 '16.64',
 '15.52',
 '0.012',
 '헝가리 HUF',
 '3.89',
 '4.25',
 '3.58',
 '3.93',
 '3.85',
 '0.003',
 '폴란드 PLN',
 '311.86',
 '336.80',
 '286.92',
 '315.29',
 '308.43',
 '0.237',
 '스리랑카 LKR',
 '4.11',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.003',
 '알제리 DZD',
 '9.70',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.007',
 '케냐 KES',
 '9.74',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.007',
 '콜롬비아 COP',
 '0.29',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '탄자니아 TZS',
 '0.56',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '네팔 NPR',
 '10.02',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.008',
 '루마니아 RON',
 '292.61',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.222',
 '리비아 LYD',
 '275.95',
 'N/A',
 'N/A',
 '278.70',
 '273.20',
 '0.210',
 '마카오 MOP',
 '162.65',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.124',
 '미얀마 MMK',
 '0.63',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.001',
 '에티오피아 ETB',
 '24.15',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.018',
 '우즈베키스탄 UZS',
 '0.12',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '캄보디아 KHR',
 '0.32',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '피지 FJD',
 '589.61',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.448']

In [34]:
# 리스트 2차원으로 나누기

# len(_list)/7        # float
len(_list) // 7       # int

58

In [35]:
# list(range(0, (len(_list)/7), 1))    : float라 오류
list(range(0, (len(_list)//7), 1))   # : int라 결과 나온다.

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57]

In [39]:
result = []
for i in range(0, (len(_list)//7), 1) :
    x = []
    for j in range(i*7, (i+1)*7, 1) :
        x.append(_list[j])
    result.append(x)
result

[['미국 USD',
  '1,315.50',
  '1,338.52',
  '1,292.48',
  '1,328.30',
  '1,302.70',
  '1.000'],
 ['유럽연합 EUR',
  '1,444.68',
  '1,473.42',
  '1,415.94',
  '1,459.12',
  '1,430.24',
  '1.098'],
 ['일본 JPY (100엔)', '981.75', '998.93', '964.57', '991.37', '972.13', '0.746'],
 ['중국 CNY', '191.29', '200.85', '181.73', '193.20', '189.38', '0.145'],
 ['홍콩 HKD', '167.60', '170.90', '164.30', '169.27', '165.93', '0.127'],
 ['대만 TWD', '43.15', '48.80', '38.84', 'N/A', 'N/A', '0.033'],
 ['영국 GBP',
  '1,635.17',
  '1,667.38',
  '1,602.96',
  '1,651.52',
  '1,618.82',
  '1.243'],
 ['오만 OMR', '3,416.71', '3,720.79', '3,211.71', 'N/A', 'N/A', '2.597'],
 ['캐나다 CAD', '982.52', '1,001.87', '963.17', '992.34', '972.70', '0.747'],
 ['스위스 CHF',
  '1,468.27',
  '1,497.19',
  '1,439.35',
  '1,482.95',
  '1,453.59',
  '1.116'],
 ['스웨덴 SEK', '127.52', '130.64', '124.40', '128.79', '126.25', '0.097'],
 ['호주 AUD', '886.58', '904.04', '869.12', '895.44', '877.72', '0.674'],
 ['뉴질랜드 NZD', '817.45', '833.55', '801.35', '825.62', '809.28', '0.621'],
 ['체코 CZK', '61.62', '66.85', '56.08', '62.29', '60.95', '0.047'],
 ['칠레 CLP', '1.66', '1.82', '1.50', 'N/A', 'N/A', '0.001'],
 ['튀르키예 TRY', '67.83', 'N/A', 'N/A', '68.57', '67.09', '0.052'],
 ['몽골 MNT', '0.37', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['이스라엘 ILS', '360.97', '397.06', '332.10', 'N/A', 'N/A', '0.274'],
 ['덴마크 DKK', '193.87', '198.61', '189.13', '195.80', '191.94', '0.147'],
 ['노르웨이 NOK', '125.50', '128.57', '122.43', '126.75', '124.25', '0.095'],
 ['사우디아라비아 SAR', '350.73', '372.82', '326.53', '354.23', '347.23', '0.267'],
 ['쿠웨이트 KWD',
  '4,292.85',
  '4,571.88',
  '3,949.43',
  '4,335.77',
  '4,249.93',
  '3.263'],
 ['바레인 BHD',
  '3,489.11',
  '3,712.41',
  '3,209.99',
  '3,524.00',
  '3,454.22',
  '2.652'],
 ['아랍에미리트 AED', '358.21', '377.91', '333.50', '361.79', '354.63', '0.272'],
 ['요르단 JOD', '1,854.38', '2,019.41', '1,706.03', 'N/A', 'N/A', '1.410'],
 ['이집트 EGP', '42.57', 'N/A', 'N/A', 'N/A', 'N/A', '0.032'],
 ['태국 THB', '38.42', '40.34', '36.12', '38.80', '38.04', '0.029'],
 ['싱가포르 SGD', '987.95', '1,007.61', '968.29', '997.82', '978.08', '0.751'],
 ['말레이시아 MYR', '297.02', '315.73', '275.05', 'N/A', '294.05', '0.226'],
 ['인도네시아 IDR 100', '8.88', '9.76', '8.00', '8.96', '8.80', '0.007'],
 ['카타르 QAR', '360.59', 'N/A', 'N/A', 'N/A', 'N/A', '0.274'],
 ['카자흐스탄 KZT', '2.91', 'N/A', 'N/A', 'N/A', 'N/A', '0.002'],
 ['브루나이 BND', '987.95', '1,027.46', '928.68', 'N/A', 'N/A', '0.751'],
 ['인도 INR', '16.02', 'N/A', 'N/A', 'N/A', 'N/A', '0.012'],
 ['파키스탄 PKR', '4.63', 'N/A', 'N/A', 'N/A', 'N/A', '0.004'],
 ['방글라데시 BDT', '12.39', 'N/A', 'N/A', 'N/A', 'N/A', '0.009'],
 ['필리핀 PHP', '23.43', '25.77', '21.51', '23.66', '23.20', '0.018'],
 ['멕시코 MXN', '72.90', '80.19', '66.78', '73.62', '72.18', '0.055'],
 ['브라질 BRL', '263.84', '290.75', '237.46', 'N/A', '260.68', '0.201'],
 ['베트남 VND 100', '5.60', '6.26', '4.94', '5.65', '5.55', '0.004'],
 ['남아프리카 공화국 ZAR', '72.54', '78.34', '66.74', '73.41', '71.67', '0.055'],
 ['러시아 RUB', '16.08', '17.60', '13.27', '16.64', '15.52', '0.012'],
 ['헝가리 HUF', '3.89', '4.25', '3.58', '3.93', '3.85', '0.003'],
 ['폴란드 PLN', '311.86', '336.80', '286.92', '315.29', '308.43', '0.237'],
 ['스리랑카 LKR', '4.11', 'N/A', 'N/A', 'N/A', 'N/A', '0.003'],
 ['알제리 DZD', '9.70', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['케냐 KES', '9.74', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['콜롬비아 COP', '0.29', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['탄자니아 TZS', '0.56', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['네팔 NPR', '10.02', 'N/A', 'N/A', 'N/A', 'N/A', '0.008'],
 ['루마니아 RON', '292.61', 'N/A', 'N/A', 'N/A', 'N/A', '0.222'],
 ['리비아 LYD', '275.95', 'N/A', 'N/A', '278.70', '273.20', '0.210'],
 ['마카오 MOP', '162.65', 'N/A', 'N/A', 'N/A', 'N/A', '0.124'],
 ['미얀마 MMK', '0.63', 'N/A', 'N/A', 'N/A', 'N/A', '0.001'],
 ['에티오피아 ETB', '24.15', 'N/A', 'N/A', 'N/A', 'N/A', '0.018'],
 ['우즈베키스탄 UZS', '0.12', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['캄보디아 KHR', '0.32', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['피지 FJD', '589.61', 'N/A', 'N/A', 'N/A', 'N/A', '0.448']]

In [40]:
# 0부터 7 전 까지
_list[0:7]

['미국 USD', '1,315.50', '1,338.52', '1,292.48', '1,328.30', '1,302.70', '1.000']

In [41]:
_list[14:21]

['일본 JPY (100엔)', '981.75', '998.93', '964.57', '991.37', '972.13', '0.746']

In [45]:
# 위 과정을 더 간단하게 해보자
result = []
for i in range(len(_list)//7) :

    result.append(_list[i*7:(i+1)*7])
result

[['미국 USD',
  '1,315.50',
  '1,338.52',
  '1,292.48',
  '1,328.30',
  '1,302.70',
  '1.000'],
 ['유럽연합 EUR',
  '1,444.68',
  '1,473.42',
  '1,415.94',
  '1,459.12',
  '1,430.24',
  '1.098'],
 ['일본 JPY (100엔)', '981.75', '998.93', '964.57', '991.37', '972.13', '0.746'],
 ['중국 CNY', '191.29', '200.85', '181.73', '193.20', '189.38', '0.145'],
 ['홍콩 HKD', '167.60', '170.90', '164.30', '169.27', '165.93', '0.127'],
 ['대만 TWD', '43.15', '48.80', '38.84', 'N/A', 'N/A', '0.033'],
 ['영국 GBP',
  '1,635.17',
  '1,667.38',
  '1,602.96',
  '1,651.52',
  '1,618.82',
  '1.243'],
 ['오만 OMR', '3,416.71', '3,720.79', '3,211.71', 'N/A', 'N/A', '2.597'],
 ['캐나다 CAD', '982.52', '1,001.87', '963.17', '992.34', '972.70', '0.747'],
 ['스위스 CHF',
  '1,468.27',
  '1,497.19',
  '1,439.35',
  '1,482.95',
  '1,453.59',
  '1.116'],
 ['스웨덴 SEK', '127.52', '130.64', '124.40', '128.79', '126.25', '0.097'],
 ['호주 AUD', '886.58', '904.04', '869.12', '895.44', '877.72', '0.674'],
 ['뉴질랜드 NZD', '817.45', '833.55', '801.35', '825.62', '809.28', '0.621'],
 ['체코 CZK', '61.62', '66.85', '56.08', '62.29', '60.95', '0.047'],
 ['칠레 CLP', '1.66', '1.82', '1.50', 'N/A', 'N/A', '0.001'],
 ['튀르키예 TRY', '67.83', 'N/A', 'N/A', '68.57', '67.09', '0.052'],
 ['몽골 MNT', '0.37', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['이스라엘 ILS', '360.97', '397.06', '332.10', 'N/A', 'N/A', '0.274'],
 ['덴마크 DKK', '193.87', '198.61', '189.13', '195.80', '191.94', '0.147'],
 ['노르웨이 NOK', '125.50', '128.57', '122.43', '126.75', '124.25', '0.095'],
 ['사우디아라비아 SAR', '350.73', '372.82', '326.53', '354.23', '347.23', '0.267'],
 ['쿠웨이트 KWD',
  '4,292.85',
  '4,571.88',
  '3,949.43',
  '4,335.77',
  '4,249.93',
  '3.263'],
 ['바레인 BHD',
  '3,489.11',
  '3,712.41',
  '3,209.99',
  '3,524.00',
  '3,454.22',
  '2.652'],
 ['아랍에미리트 AED', '358.21', '377.91', '333.50', '361.79', '354.63', '0.272'],
 ['요르단 JOD', '1,854.38', '2,019.41', '1,706.03', 'N/A', 'N/A', '1.410'],
 ['이집트 EGP', '42.57', 'N/A', 'N/A', 'N/A', 'N/A', '0.032'],
 ['태국 THB', '38.42', '40.34', '36.12', '38.80', '38.04', '0.029'],
 ['싱가포르 SGD', '987.95', '1,007.61', '968.29', '997.82', '978.08', '0.751'],
 ['말레이시아 MYR', '297.02', '315.73', '275.05', 'N/A', '294.05', '0.226'],
 ['인도네시아 IDR 100', '8.88', '9.76', '8.00', '8.96', '8.80', '0.007'],
 ['카타르 QAR', '360.59', 'N/A', 'N/A', 'N/A', 'N/A', '0.274'],
 ['카자흐스탄 KZT', '2.91', 'N/A', 'N/A', 'N/A', 'N/A', '0.002'],
 ['브루나이 BND', '987.95', '1,027.46', '928.68', 'N/A', 'N/A', '0.751'],
 ['인도 INR', '16.02', 'N/A', 'N/A', 'N/A', 'N/A', '0.012'],
 ['파키스탄 PKR', '4.63', 'N/A', 'N/A', 'N/A', 'N/A', '0.004'],
 ['방글라데시 BDT', '12.39', 'N/A', 'N/A', 'N/A', 'N/A', '0.009'],
 ['필리핀 PHP', '23.43', '25.77', '21.51', '23.66', '23.20', '0.018'],
 ['멕시코 MXN', '72.90', '80.19', '66.78', '73.62', '72.18', '0.055'],
 ['브라질 BRL', '263.84', '290.75', '237.46', 'N/A', '260.68', '0.201'],
 ['베트남 VND 100', '5.60', '6.26', '4.94', '5.65', '5.55', '0.004'],
 ['남아프리카 공화국 ZAR', '72.54', '78.34', '66.74', '73.41', '71.67', '0.055'],
 ['러시아 RUB', '16.08', '17.60', '13.27', '16.64', '15.52', '0.012'],
 ['헝가리 HUF', '3.89', '4.25', '3.58', '3.93', '3.85', '0.003'],
 ['폴란드 PLN', '311.86', '336.80', '286.92', '315.29', '308.43', '0.237'],
 ['스리랑카 LKR', '4.11', 'N/A', 'N/A', 'N/A', 'N/A', '0.003'],
 ['알제리 DZD', '9.70', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['케냐 KES', '9.74', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['콜롬비아 COP', '0.29', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['탄자니아 TZS', '0.56', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['네팔 NPR', '10.02', 'N/A', 'N/A', 'N/A', 'N/A', '0.008'],
 ['루마니아 RON', '292.61', 'N/A', 'N/A', 'N/A', 'N/A', '0.222'],
 ['리비아 LYD', '275.95', 'N/A', 'N/A', '278.70', '273.20', '0.210'],
 ['마카오 MOP', '162.65', 'N/A', 'N/A', 'N/A', 'N/A', '0.124'],
 ['미얀마 MMK', '0.63', 'N/A', 'N/A', 'N/A', 'N/A', '0.001'],
 ['에티오피아 ETB', '24.15', 'N/A', 'N/A', 'N/A', 'N/A', '0.018'],
 ['우즈베키스탄 UZS', '0.12', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['캄보디아 KHR', '0.32', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['피지 FJD', '589.61', 'N/A', 'N/A', 'N/A', 'N/A', '0.448']]

In [46]:
import pandas as pd

In [49]:
columns = ['통화명', '매매기준율', '현찰(구매)', '현찰(판매)', '송금(보낼때)', '송금(받을때)', '미화환산율']

In [51]:
pd.DataFrame(result, columns = columns).to_csv("test.csv", index = False)

In [52]:
pd.read_csv("test.csv")

              통화명     매매기준율    현찰(구매)    현찰(판매)   송금(보낼때)   송금(받을때)  미화환산율
0          미국 USD  1,315.50  1,338.52  1,292.48  1,328.30  1,302.70  1.000
1        유럽연합 EUR  1,444.68  1,473.42  1,415.94  1,459.12  1,430.24  1.098
2   일본 JPY (100엔)    981.75    998.93    964.57    991.37    972.13  0.746
3          중국 CNY    191.29    200.85    181.73    193.20    189.38  0.145
4          홍콩 HKD    167.60    170.90    164.30    169.27    165.93  0.127
5          대만 TWD     43.15     48.80     38.84       NaN       NaN  0.033
6          영국 GBP  1,635.17  1,667.38  1,602.96  1,651.52  1,618.82  1.243
7          오만 OMR  3,416.71  3,720.79  3,211.71       NaN       NaN  2.597
8         캐나다 CAD    982.52  1,001.87    963.17    992.34    972.70  0.747
9         스위스 CHF  1,468.27  1,497.19  1,439.35  1,482.95  1,453.59  1.116
10        스웨덴 SEK    127.52    130.64    124.40    128.79    126.25  0.097
11         호주 AUD    886.58    904.04    869.12    895.44    877.72  0.674
12       뉴질랜드 NZD    817.45    833.55    801.35    825.62    809.28  0.621
13         체코 CZK     61.62     66.85     56.08     62.29     60.95  0.047
14         칠레 CLP      1.66      1.82      1.50       NaN       NaN  0.001
15       튀르키예 TRY     67.83       NaN       NaN     68.57     67.09  0.052
16         몽골 MNT      0.37       NaN       NaN       NaN       NaN  0.000
17       이스라엘 ILS    360.97    397.06    332.10       NaN       NaN  0.274
18        덴마크 DKK    193.87    198.61    189.13    195.80    191.94  0.147
19       노르웨이 NOK    125.50    128.57    122.43    126.75    124.25  0.095
20    사우디아라비아 SAR    350.73    372.82    326.53    354.23    347.23  0.267
21       쿠웨이트 KWD  4,292.85  4,571.88  3,949.43  4,335.77  4,249.93  3.263
22        바레인 BHD  3,489.11  3,712.41  3,209.99  3,524.00  3,454.22  2.652
23     아랍에미리트 AED    358.21    377.91    333.50    361.79    354.63  0.272
24        요르단 JOD  1,854.38  2,019.41  1,706.03       NaN       NaN  1.410
25        이집트 EGP     42.57       NaN       NaN       NaN       NaN  0.032
26         태국 THB     38.42     40.34     36.12     38.80     38.04  0.029
27       싱가포르 SGD    987.95  1,007.61    968.29    997.82    978.08  0.751
28      말레이시아 MYR    297.02    315.73    275.05       NaN    294.05  0.226
29  인도네시아 IDR 100      8.88      9.76      8.00      8.96      8.80  0.007
30        카타르 QAR    360.59       NaN       NaN       NaN       NaN  0.274
31      카자흐스탄 KZT      2.91       NaN       NaN       NaN       NaN  0.002
32       브루나이 BND    987.95  1,027.46    928.68       NaN       NaN  0.751
33         인도 INR     16.02       NaN       NaN       NaN       NaN  0.012
34       파키스탄 PKR      4.63       NaN       NaN       NaN       NaN  0.004
35      방글라데시 BDT     12.39       NaN       NaN       NaN       NaN  0.009
36        필리핀 PHP     23.43     25.77     21.51     23.66     23.20  0.018
37        멕시코 MXN     72.90     80.19     66.78     73.62     72.18  0.055
38        브라질 BRL    263.84    290.75    237.46       NaN    260.68  0.201
39    베트남 VND 100      5.60      6.26      4.94      5.65      5.55  0.004
40  남아프리카 공화국 ZAR     72.54     78.34     66.74     73.41     71.67  0.055
41        러시아 RUB     16.08     17.60     13.27     16.64     15.52  0.012
42        헝가리 HUF      3.89      4.25      3.58      3.93      3.85  0.003
43        폴란드 PLN    311.86    336.80    286.92    315.29    308.43  0.237
44       스리랑카 LKR      4.11       NaN       NaN       NaN       NaN  0.003
45        알제리 DZD      9.70       NaN       NaN       NaN       NaN  0.007
46         케냐 KES      9.74       NaN       NaN       NaN       NaN  0.007
47       콜롬비아 COP      0.29       NaN       NaN       NaN       NaN  0.000
48       탄자니아 TZS      0.56       NaN       NaN       NaN       NaN  0.000
49         네팔 NPR     10.02       NaN       NaN       NaN       NaN  0.008
50       루마니아 RON    292.61       NaN       NaN       NaN       NaN  0.222
51        리비아 LYD    275.95       NaN       NaN    278.70    273.20  0.210
52        마카오 MOP    162.65       NaN       NaN       NaN       NaN  0.124
53        미얀마 MMK      0.63       NaN       NaN       NaN       NaN  0.001
54      에티오피아 ETB     24.15       NaN       NaN       NaN       NaN  0.018
55     우즈베키스탄 UZS      0.12       NaN       NaN       NaN       NaN  0.000
56       캄보디아 KHR      0.32       NaN       NaN       NaN       NaN  0.000
57         피지 FJD    589.61       NaN       NaN       NaN       NaN  0.448

sql로 받아오기

In [60]:
import mod_sql

In [61]:
db = mod_sql.Database('localhost', 'root', '1234', 'ubion7', 3306)

In [58]:
# DB에 table 행성 (naver)
# 필드는 7개 모두 필드의 타입은 문자열 구성
# 통화명 필드는 primary key

sql = """
    create
    table
    `naver` (
        `통화명` varchar(16) primary key,
        `매매기준율` varchar(16),
        `현찰(구매)` varchar(16),
        `현찰(판매)` varchar(16),
        `송금(보낼때)` varchar(16),
        `송금(받을때)` varchar(16),
        `미화환산율` varchar(16)
    )
"""
db.sql_query(sql)

'Query OK'

In [63]:
# naver라는 이름으로 생성한 테이블에 데이터 삽입
# 데이터를 삽입하는 insert문을 작성

sql = """
    insert
    into
    `naver` 
    values (
        '미국 USD',
        '1,315.50',
        '1,338.52',
        '1,292.48',
        '1,328.30',
        '1,302.70',
        '1.000'
    )
    
"""
db.sql_query(sql)

'Query OK'

In [66]:
# 또 다른 방법
sql = """
    insert
    into
    naver
    values
    (%s, %s, %s, %s, %s, %s, %s)
"""
values = ['유럽연합 EUR', '1,444.68', '1,473.42', '1,415.94', '1,459.12', '1,430.24', '1.098']

db.sql_query(sql, values)

'Query OK'

In [67]:
sql = """
    select
    *
    from
    `naver`
"""
db.sql_query(sql)

        통화명     매매기준율    현찰(구매)    현찰(판매)   송금(보낼때)   송금(받을때)  미화환산율
0    미국 USD  1,315.50  1,338.52  1,292.48  1,328.30  1,302.70  1.000
1  유럽연합 EUR  1,444.68  1,473.42  1,415.94  1,459.12  1,430.24  1.098

In [68]:
# 입력한 데이터 삭제

sql = """
    delete
    from
    `naver`
    where
    `통화명` = '미국 USD'
"""

db.sql_query(sql)

# delete는 테이블 안의 값을 삭제,
# drop은 테이블 자체를 삭제

'Query OK'

In [71]:
sql = """
    delete
    from
    `naver`
    where
    `통화명` = '유럽연합 EUR'
"""

db.sql_query(sql)

'Query OK'

In [72]:
sql = """
    select
    *
    from
    `naver`
"""
db.sql_query(sql)

Empty DataFrame
Columns: []
Index: []

In [70]:
result[0]

['미국 USD', '1,315.50', '1,338.52', '1,292.48', '1,328.30', '1,302.70', '1.000']

In [78]:
# result 변수의 데이터를 naver 테이블 삽입

isql = """
    insert
    into
    naver
    values
    (%s, %s, %s, %s, %s, %s, %s)
"""

for i in result :
    values = db.sql_query(isql, i)

In [80]:
sql = """
    select
    *
    from
    `naver`
"""

db.sql_query(sql)

              통화명     매매기준율    현찰(구매)    현찰(판매)   송금(보낼때)   송금(받을때)  미화환산율
0   남아프리카 공화국 ZAR     72.54     78.34     66.74     73.41     71.67  0.055
1          네팔 NPR     10.02       N/A       N/A       N/A       N/A  0.008
2        노르웨이 NOK    125.50    128.57    122.43    126.75    124.25  0.095
3        뉴질랜드 NZD    817.45    833.55    801.35    825.62    809.28  0.621
4          대만 TWD     43.15     48.80     38.84       N/A       N/A  0.033
5         덴마크 DKK    193.87    198.61    189.13    195.80    191.94  0.147
6         러시아 RUB     16.08     17.60     13.27     16.64     15.52  0.012
7        루마니아 RON    292.61       N/A       N/A       N/A       N/A  0.222
8         리비아 LYD    275.95       N/A       N/A    278.70    273.20  0.210
9         마카오 MOP    162.65       N/A       N/A       N/A       N/A  0.124
10      말레이시아 MYR    297.02    315.73    275.05       N/A    294.05  0.226
11        멕시코 MXN     72.90     80.19     66.78     73.62     72.18  0.055
12         몽골 MNT      0.37       N/A       N/A       N/A       N/A  0.000
13         미국 USD  1,315.50  1,338.52  1,292.48  1,328.30  1,302.70  1.000
14        미얀마 MMK      0.63       N/A       N/A       N/A       N/A  0.001
15        바레인 BHD  3,489.11  3,712.41  3,209.99  3,524.00  3,454.22  2.652
16      방글라데시 BDT     12.39       N/A       N/A       N/A       N/A  0.009
17    베트남 VND 100      5.60      6.26      4.94      5.65      5.55  0.004
18        브라질 BRL    263.84    290.75    237.46       N/A    260.68  0.201
19       브루나이 BND    987.95  1,027.46    928.68       N/A       N/A  0.751
20    사우디아라비아 SAR    350.73    372.82    326.53    354.23    347.23  0.267
21       스리랑카 LKR      4.11       N/A       N/A       N/A       N/A  0.003
22        스웨덴 SEK    127.52    130.64    124.40    128.79    126.25  0.097
23        스위스 CHF  1,468.27  1,497.19  1,439.35  1,482.95  1,453.59  1.116
24       싱가포르 SGD    987.95  1,007.61    968.29    997.82    978.08  0.751
25     아랍에미리트 AED    358.21    377.91    333.50    361.79    354.63  0.272
26        알제리 DZD      9.70       N/A       N/A       N/A       N/A  0.007
27      에티오피아 ETB     24.15       N/A       N/A       N/A       N/A  0.018
28         영국 GBP  1,635.17  1,667.38  1,602.96  1,651.52  1,618.82  1.243
29         오만 OMR  3,416.71  3,720.79  3,211.71       N/A       N/A  2.597
30        요르단 JOD  1,854.38  2,019.41  1,706.03       N/A       N/A  1.410
31     우즈베키스탄 UZS      0.12       N/A       N/A       N/A       N/A  0.000
32       유럽연합 EUR  1,444.68  1,473.42  1,415.94  1,459.12  1,430.24  1.098
33       이스라엘 ILS    360.97    397.06    332.10       N/A       N/A  0.274
34        이집트 EGP     42.57       N/A       N/A       N/A       N/A  0.032
35         인도 INR     16.02       N/A       N/A       N/A       N/A  0.012
36  인도네시아 IDR 100      8.88      9.76      8.00      8.96      8.80  0.007
37  일본 JPY (100엔)    981.75    998.93    964.57    991.37    972.13  0.746
38         중국 CNY    191.29    200.85    181.73    193.20    189.38  0.145
39         체코 CZK     61.62     66.85     56.08     62.29     60.95  0.047
40         칠레 CLP      1.66      1.82      1.50       N/A       N/A  0.001
41      카자흐스탄 KZT      2.91       N/A       N/A       N/A       N/A  0.002
42        카타르 QAR    360.59       N/A       N/A       N/A       N/A  0.274
43       캄보디아 KHR      0.32       N/A       N/A       N/A       N/A  0.000
44        캐나다 CAD    982.52  1,001.87    963.17    992.34    972.70  0.747
45         케냐 KES      9.74       N/A       N/A       N/A       N/A  0.007
46       콜롬비아 COP      0.29       N/A       N/A       N/A       N/A  0.000
47       쿠웨이트 KWD  4,292.85  4,571.88  3,949.43  4,335.77  4,249.93  3.263
48       탄자니아 TZS      0.56       N/A       N/A       N/A       N/A  0.000
49         태국 THB     38.42     40.34     36.12     38.80     38.04  0.029
50       튀르키예 TRY     67.83       N/A       N/A     68.57     67.09  0.052
51       파키스탄 PKR      4.63       N/A       N/A       N/A       N/A  0.004
52        폴란드 PLN    311.86    336.80    286.92    315.29    308.43  0.237
53         피지 FJD    589.61       N/A       N/A       N/A       N/A  0.448
54        필리핀 PHP     23.43     25.77     21.51     23.66     23.20  0.018
55        헝가리 HUF      3.89      4.25      3.58      3.93      3.85  0.003
56         호주 AUD    886.58    904.04    869.12    895.44    877.72  0.674
57         홍콩 HKD    167.60    170.90    164.30    169.27    165.93  0.127

In [81]:
sql = """
    delete
    from
    `naver`
"""
db.sql_query(sql)

'Query OK'

In [82]:
# 교수님 풀이

sql = """
    insert
    into
    naver
    values
    (%s, %s, %s, %s, %s, %s, %s)
"""

for i in range(len(result)) :
    values = result[i]
    db.sql_query(sql, values)

In [83]:
sql = """
    select * from `naver`
"""
db.sql_query(sql)

              통화명     매매기준율    현찰(구매)    현찰(판매)   송금(보낼때)   송금(받을때)  미화환산율
0   남아프리카 공화국 ZAR     72.54     78.34     66.74     73.41     71.67  0.055
1          네팔 NPR     10.02       N/A       N/A       N/A       N/A  0.008
2        노르웨이 NOK    125.50    128.57    122.43    126.75    124.25  0.095
3        뉴질랜드 NZD    817.45    833.55    801.35    825.62    809.28  0.621
4          대만 TWD     43.15     48.80     38.84       N/A       N/A  0.033
5         덴마크 DKK    193.87    198.61    189.13    195.80    191.94  0.147
6         러시아 RUB     16.08     17.60     13.27     16.64     15.52  0.012
7        루마니아 RON    292.61       N/A       N/A       N/A       N/A  0.222
8         리비아 LYD    275.95       N/A       N/A    278.70    273.20  0.210
9         마카오 MOP    162.65       N/A       N/A       N/A       N/A  0.124
10      말레이시아 MYR    297.02    315.73    275.05       N/A    294.05  0.226
11        멕시코 MXN     72.90     80.19     66.78     73.62     72.18  0.055
12         몽골 MNT      0.37       N/A       N/A       N/A       N/A  0.000
13         미국 USD  1,315.50  1,338.52  1,292.48  1,328.30  1,302.70  1.000
14        미얀마 MMK      0.63       N/A       N/A       N/A       N/A  0.001
15        바레인 BHD  3,489.11  3,712.41  3,209.99  3,524.00  3,454.22  2.652
16      방글라데시 BDT     12.39       N/A       N/A       N/A       N/A  0.009
17    베트남 VND 100      5.60      6.26      4.94      5.65      5.55  0.004
18        브라질 BRL    263.84    290.75    237.46       N/A    260.68  0.201
19       브루나이 BND    987.95  1,027.46    928.68       N/A       N/A  0.751
20    사우디아라비아 SAR    350.73    372.82    326.53    354.23    347.23  0.267
21       스리랑카 LKR      4.11       N/A       N/A       N/A       N/A  0.003
22        스웨덴 SEK    127.52    130.64    124.40    128.79    126.25  0.097
23        스위스 CHF  1,468.27  1,497.19  1,439.35  1,482.95  1,453.59  1.116
24       싱가포르 SGD    987.95  1,007.61    968.29    997.82    978.08  0.751
25     아랍에미리트 AED    358.21    377.91    333.50    361.79    354.63  0.272
26        알제리 DZD      9.70       N/A       N/A       N/A       N/A  0.007
27      에티오피아 ETB     24.15       N/A       N/A       N/A       N/A  0.018
28         영국 GBP  1,635.17  1,667.38  1,602.96  1,651.52  1,618.82  1.243
29         오만 OMR  3,416.71  3,720.79  3,211.71       N/A       N/A  2.597
30        요르단 JOD  1,854.38  2,019.41  1,706.03       N/A       N/A  1.410
31     우즈베키스탄 UZS      0.12       N/A       N/A       N/A       N/A  0.000
32       유럽연합 EUR  1,444.68  1,473.42  1,415.94  1,459.12  1,430.24  1.098
33       이스라엘 ILS    360.97    397.06    332.10       N/A       N/A  0.274
34        이집트 EGP     42.57       N/A       N/A       N/A       N/A  0.032
35         인도 INR     16.02       N/A       N/A       N/A       N/A  0.012
36  인도네시아 IDR 100      8.88      9.76      8.00      8.96      8.80  0.007
37  일본 JPY (100엔)    981.75    998.93    964.57    991.37    972.13  0.746
38         중국 CNY    191.29    200.85    181.73    193.20    189.38  0.145
39         체코 CZK     61.62     66.85     56.08     62.29     60.95  0.047
40         칠레 CLP      1.66      1.82      1.50       N/A       N/A  0.001
41      카자흐스탄 KZT      2.91       N/A       N/A       N/A       N/A  0.002
42        카타르 QAR    360.59       N/A       N/A       N/A       N/A  0.274
43       캄보디아 KHR      0.32       N/A       N/A       N/A       N/A  0.000
44        캐나다 CAD    982.52  1,001.87    963.17    992.34    972.70  0.747
45         케냐 KES      9.74       N/A       N/A       N/A       N/A  0.007
46       콜롬비아 COP      0.29       N/A       N/A       N/A       N/A  0.000
47       쿠웨이트 KWD  4,292.85  4,571.88  3,949.43  4,335.77  4,249.93  3.263
48       탄자니아 TZS      0.56       N/A       N/A       N/A       N/A  0.000
49         태국 THB     38.42     40.34     36.12     38.80     38.04  0.029
50       튀르키예 TRY     67.83       N/A       N/A     68.57     67.09  0.052
51       파키스탄 PKR      4.63       N/A       N/A       N/A       N/A  0.004
52        폴란드 PLN    311.86    336.80    286.92    315.29    308.43  0.237
53         피지 FJD    589.61       N/A       N/A       N/A       N/A  0.448
54        필리핀 PHP     23.43     25.77     21.51     23.66     23.20  0.018
55        헝가리 HUF      3.89      4.25      3.58      3.93      3.85  0.003
56         호주 AUD    886.58    904.04    869.12    895.44    877.72  0.674
57         홍콩 HKD    167.60    170.90    164.30    169.27    165.93  0.127

In [103]:
# naver2에도 값 입력해보기
sql = """
    insert
    into
    naver2
    (`통화명`, `매매기준율`, `현찰(구매)`, `현찰(판매)`, `송금(보낼때)`, `송금(받을때)`, `미화환산율`)
    values
    (%s, %s, %s, %s, %s, %s, %s)
"""

for i in result :
    db.sql_query(sql, i)

In [101]:
sql = """
    delete
    from
    `naver2`
"""
db.sql_query(sql)

'Query OK'

In [104]:
sql = """
    select
    *
    from
    naver2
"""
db.sql_query(sql)

# no 컬럼을 AI(Auto Increament) 로 설정하면, delete 했다가 다시 추가하더라도, 초기화되지 않는다.
# ex. 게시판 게시글 번호라고 생각. 1번 게시글을 삭제하더라도 해당 번호를 다른 게시글이 가져가지 않는다.

,no,통화명,매매기준율,현찰(구매),현찰(판매),송금(보낼때),송금(받을때),미화환산율
0,118,미국 USD,"1,315.50","1,338.52","1,292.48","1,328.30","1,302.70",1.000
1,119,유럽연합 EUR,"1,444.68","1,473.42","1,415.94","1,459.12","1,430.24",1.098
2,120,일본 JPY (100엔),981.75,998.93,964.57,991.37,972.13,0.746
3,121,중국 CNY,191.29,200.85,181.73,193.20,189.38,0.145
4,122,홍콩 HKD,167.60,170.90,164.30,169.27,165.93,0.127
5,123,대만 TWD,43.15,48.80,38.84,N/A,N/A,0.033
6,124,영국 GBP,"1,635.17","1,667.38","1,602.96","1,651.52","1,618.82",1.243
7,125,오만 OMR,"3,416.71","3,720.79","3,211.71",N/A,N/A,2.597
8,126,캐나다 CAD,982.52,"1,001.87",963.17,992.34,972.70,0.747
9,127,스위스 CHF,"1,468.27","1,497.19","1,439.35","1,482.95","1,453.59",1.116
10,128,스웨덴 SEK,127.52,130.64,124.40,128.79,126.25,0.097
11,129,호주 AUD,886.58,904.04,869.12,895.44,877.72,0.674
12,130,뉴질랜드 NZD,817.45,833.55,801.35,825.62,809.28,0.621
13,131,체코 CZK,61.62,66.85,56.08,62.29,60.95,0.047
14,132,칠레 CLP,1.66,1.82,1.50,N/A,N/A,0.001
15,133,튀르키예 TRY,67.83,N/A,N/A,68.57,67.09,0.052
16,134,몽골 MNT,0.37,N/A,N/A,N/A,N/A,0.000
17,135,이스라엘 ILS,360.97,397.06,332.10,N/A,N/A,0.274
18,136,덴마크 DKK,193.87,198.61,189.13,195.80,191.94,0.147
19,137,노르웨이 NOK,125.50,128.57,122.43,126.75,124.25,0.095
20,138,사우디아라비아 SAR,350.73,372.82,326.53,354.23,347.23,0.267
21,139,쿠웨이트 KWD,"4,292.85","4,571.88","3,949.43","4,335.77","4,249.93",3.263
22,140,바레인 BHD,"3,489.11","3,712.41","3,209.99","3,524.00","3,454.22",2.652
23,141,아랍에미리트 AED,358.21,377.91,333.50,361.79,354.63,0.272
24,142,요르단 JOD,"1,854.38","2,019.41","1,706.03",N/A,N/A,1.410
25,143,이집트 EGP,42.57,N/A,N/A,N/A,N/A,0.032
26,144,태국 THB,38.42,40.34,36.12,38.80,38.04,0.029
27,145,싱가포르 SGD,987.95,"1,007.61",968.29,997.82,978.08,0.751
28,146,말레이시아 MYR,297.02,315.73,275.05,N/A,294.05,0.226
29,147,인도네시아 IDR 100,8.88,9.76,8.00,8.96,8.80,0.007
30,148,카타르 QAR,360.59,N/A,N/A,N/A,N/A,0.274
31,149,카자흐스탄 KZT,2.91,N/A,N/A,N/A,N/A,0.002
32,150,브루나이 BND,987.95,"1,027.46",928.68,N/A,N/A,0.751
33,151,인도 INR,16.02,N/A,N/A,N/A,N/A,0.012
34,152,파키스탄 PKR,4.63,N/A,N/A,N/A,N/A,0.004
35,153,방글라데시 BDT,12.39,N/A,N/A,N/A,N/A,0.009
36,154,필리핀 PHP,23.43,25.77,21.51,23.66,23.20,0.018
37,155,멕시코 MXN,72.90,80.19,66.78,73.62,72.18,0.055
38,156,브라질 BRL,263.84,290.75,237.46,N/A,260.68,0.201
39,157,베트남 VND 100,5.60,6.26,4.94,5.65,5.55,0.004
40,158,남아프리카 공화국 ZAR,72.54,78.34,66.74,73.41,71.67,0.055
41,159,러시아 RUB,16.08,17.60,13.27,16.64,15.52,0.012
42,160,헝가리 HUF,3.89,4.25,3.58,3.93,3.85,0.003
43,161,폴란드 PLN,311.86,336.80,286.92,315.29,308.43,0.237
44,162,스리랑카 LKR,4.11,N/A,N/A,N/A,N/A,0.003
45,163,알제리 DZD,9.70,N/A,N/A,N/A,N/A,0.007
46,164,케냐 KES,9.74,N/A,N/A,N/A,N/A,0.007
47,165,콜롬비아 COP,0.29,N/A,N/A,N/A,N/A,0.000
48,166,탄자니아 TZS,0.56,N/A,N/A,N/A,N/A,0.000
49,167,네팔 NPR,10.02,N/A,N/A,N/A,N/A,0.008
50,168,루마니아 RON,292.61,N/A,N/A,N/A,N/A,0.222
51,169,리비아 LYD,275.95,N/A,N/A,278.70,273.20,0.210
52,170,마카오 MOP,162.65,N/A,N/A,N/A,N/A,0.124
53,171,미얀마 MMK,0.63,N/A,N/A,N/A,N/A,0.001
54,172,에티오피아 ETB,24.15,N/A,N/A,N/A,N/A,0.018
55,173,우즈베키스탄 UZS,0.12,N/A,N/A,N/A,N/A,0.000
56,174,캄보디아 KHR,0.32,N/A,N/A,N/A,N/A,0.000
57,175,피지 FJD,589.61,N/A,N/A,N/A,N/A,0.448